create table MOCK_DATA (
	AmenityID INT,
	PropertyID INT,
	amenity VARCHAR(12),
	AvailabilityStatus VARCHAR(50),
	Description VARCHAR(58)
),
 (1, 184, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (2, 153, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (3, 162, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (4, 84, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (5, 277, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (6, 58, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (7, 48, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (8, 201, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (9, 76, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (10, 261, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (11, 236, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (12, 3, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (13, 253, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (14, 189, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (15, 53, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (16, 46, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (17, 168, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (18, 238, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (19, 144, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (20, 138, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (21, 209, 'playground', false, 'Kids will love our fun and safe playground'),
 (22, 72, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (23, 212, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (24, 234, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (25, 10, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (26, 131, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (27, 183, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (28, 205, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (29, 111, 'parking', true, 'Convenient & secure parking available'),
 (30, 110, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (31, 157, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (32, 74, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (33, 171, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (34, 112, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (35, 35, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (36, 101, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (37, 228, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (38, 102, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (39, 206, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (40, 220, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (41, 174, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (42, 73, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (43, 141, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (44, 147, 'playground', false, 'Kids will love our fun and safe playground'),
 (45, 185, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (46, 255, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (47, 54, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (48, 220, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (49, 122, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (50, 206, 'playground', true, 'Kids will love our fun and safe playground'),
 (51, 25, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (52, 123, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (53, 46, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (54, 113, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (55, 155, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (56, 92, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (57, 160, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (58, 170, 'parking', false, 'Convenient & secure parking available'),
 (59, 83, 'parking', false, 'Convenient & secure parking available'),
 (60, 212, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (61, 151, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (62, 265, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (63, 174, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (64, 12, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (65, 214, 'playground', false, 'Kids will love our fun and safe playground'),
 (66, 242, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (67, 202, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (68, 265, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (69, 178, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (70, 62, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (71, 61, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (72, 145, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (73, 129, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (74, 203, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (75, 164, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (76, 278, 'parking', false, 'Convenient & secure parking available'),
 (77, 108, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (78, 62, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (79, 165, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (80, 169, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (81, 251, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (82, 231, 'parking', false, 'Convenient & secure parking available'),
 (83, 33, 'parking', false, 'Convenient & secure parking available'),
 (84, 105, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (85, 129, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (86, 250, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (87, 56, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (88, 216, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (89, 234, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (90, 226, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (91, 113, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (92, 10, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (93, 147, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (94, 154, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (95, 135, 'parking', true, 'Convenient & secure parking available'),
 (96, 208, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (97, 141, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (98, 264, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (99, 69, 'parking', false, 'Convenient & secure parking available'),
 (100, 123, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (101, 94, 'parking', false, 'Convenient & secure parking available'),
 (102, 59, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (103, 126, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (104, 222, 'playground', true, 'Kids will love our fun and safe playground'),
 (105, 39, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (106, 149, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (107, 257, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (108, 7, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (109, 246, 'playground', false, 'Kids will love our fun and safe playground'),
 (110, 123, 'parking', true, 'Convenient & secure parking available'),
 (111, 279, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (112, 170, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (113, 225, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (114, 45, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (115, 198, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (116, 90, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (117, 135, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (118, 89, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (119, 44, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (120, 174, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (121, 164, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (122, 21, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (123, 192, 'playground', false, 'Kids will love our fun and safe playground'),
 (124, 13, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (125, 221, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (126, 193, 'playground', false, 'Kids will love our fun and safe playground'),
 (127, 23, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (128, 108, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (129, 220, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (130, 31, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (131, 217, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (132, 220, 'parking', false, 'Convenient & secure parking available'),
 (133, 93, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (134, 177, 'parking', true, 'Convenient & secure parking available'),
 (135, 198, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (136, 206, 'playground', true, 'Kids will love our fun and safe playground'),
 (137, 117, 'parking', false, 'Convenient & secure parking available'),
 (138, 62, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (139, 188, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (140, 77, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (141, 48, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (142, 259, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (143, 27, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (144, 118, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (145, 171, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (146, 54, 'playground', true, 'Kids will love our fun and safe playground'),
 (147, 115, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (148, 220, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (149, 53, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (150, 133, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (151, 39, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (152, 36, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (153, 33, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (154, 263, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (155, 209, 'playground', true, 'Kids will love our fun and safe playground'),
 (156, 145, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (157, 185, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (158, 140, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (159, 119, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (160, 36, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (161, 218, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (162, 248, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (163, 106, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (164, 160, 'playground', true, 'Kids will love our fun and safe playground'),
 (165, 176, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (166, 280, 'parking', true, 'Convenient & secure parking available'),
 (167, 78, 'parking', true, 'Convenient & secure parking available'),
 (168, 244, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (169, 57, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (170, 48, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (171, 35, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (172, 278, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (173, 52, 'playground', false, 'Kids will love our fun and safe playground'),
 (174, 115, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (175, 110, 'playground', true, 'Kids will love our fun and safe playground'),
 (176, 110, 'playground', true, 'Kids will love our fun and safe playground'),
 (177, 62, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (178, 155, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (179, 12, 'parking', true, 'Convenient & secure parking available'),
 (180, 142, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (181, 149, 'parking', false, 'Convenient & secure parking available'),
 (182, 253, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (183, 247, 'playground', true, 'Kids will love our fun and safe playground'),
 (184, 51, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (185, 139, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (186, 222, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (187, 196, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (188, 213, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (189, 222, 'playground', true, 'Kids will love our fun and safe playground'),
 (190, 54, 'parking', false, 'Convenient & secure parking available'),
 (191, 237, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (192, 212, 'playground', true, 'Kids will love our fun and safe playground'),
 (193, 93, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (194, 272, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (195, 229, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (196, 142, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (197, 65, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (198, 261, 'parking', false, 'Convenient & secure parking available'),
 (199, 245, 'parking', true, 'Convenient & secure parking available'),
 (200, 63, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (201, 114, 'playground', true, 'Kids will love our fun and safe playground'),
 (202, 125, 'parking', false, 'Convenient & secure parking available'),
 (203, 276, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (204, 237, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (205, 200, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (206, 192, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (207, 39, 'playground', false, 'Kids will love our fun and safe playground'),
 (208, 60, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (209, 156, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (210, 170, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (211, 113, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (212, 10, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (213, 262, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (214, 64, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (215, 131, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (216, 164, 'playground', false, 'Kids will love our fun and safe playground'),
 (217, 273, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (218, 84, 'playground', false, 'Kids will love our fun and safe playground'),
 (219, 215, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (220, 77, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (221, 70, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (222, 186, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (223, 222, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (224, 57, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (225, 111, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (226, 269, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (227, 12, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (228, 25, 'playground', true, 'Kids will love our fun and safe playground'),
 (229, 123, 'parking', true, 'Convenient & secure parking available'),
 (230, 65, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (231, 99, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (232, 112, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (233, 69, 'parking', false, 'Convenient & secure parking available'),
 (234, 53, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (235, 207, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (236, 227, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (237, 263, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (238, 231, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (239, 57, 'playground', true, 'Kids will love our fun and safe playground'),
 (240, 183, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (241, 69, 'playground', true, 'Kids will love our fun and safe playground'),
 (242, 77, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (243, 210, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (244, 112, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (245, 38, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (246, 108, 'playground', true, 'Kids will love our fun and safe playground'),
 (247, 85, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (248, 71, 'parking', false, 'Convenient & secure parking available'),
 (249, 152, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (250, 49, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (251, 255, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (252, 215, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (253, 176, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (254, 72, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (255, 97, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (256, 51, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (257, 88, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (258, 74, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (259, 164, 'playground', false, 'Kids will love our fun and safe playground'),
 (260, 101, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (261, 13, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (262, 244, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (263, 266, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (264, 167, 'parking', true, 'Convenient & secure parking available'),
 (265, 115, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (266, 42, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (267, 89, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (268, 56, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (269, 167, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (270, 97, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (271, 109, 'parking', false, 'Convenient & secure parking available'),
 (272, 151, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (273, 223, 'parking', true, 'Convenient & secure parking available'),
 (274, 191, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (275, 132, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (276, 68, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (277, 45, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (278, 209, 'playground', true, 'Kids will love our fun and safe playground'),
 (279, 132, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (280, 71, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (281, 79, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (282, 5, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (283, 195, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (284, 117, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (285, 116, 'playground', true, 'Kids will love our fun and safe playground'),
 (286, 78, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (287, 278, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (288, 212, 'parking', false, 'Convenient & secure parking available'),
 (289, 2, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (290, 128, 'playground', false, 'Kids will love our fun and safe playground'),
 (291, 55, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (292, 206, 'parking', true, 'Convenient & secure parking available'),
 (293, 138, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (294, 5, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (295, 264, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (296, 144, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (297, 140, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (298, 67, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (299, 71, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (300, 62, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (301, 157, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (302, 261, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (303, 146, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (304, 231, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (305, 155, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (306, 274, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (307, 227, 'playground', true, 'Kids will love our fun and safe playground'),
 (308, 184, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (309, 202, 'parking', false, 'Convenient & secure parking available'),
 (310, 195, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (311, 103, 'playground', false, 'Kids will love our fun and safe playground'),
 (312, 271, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (313, 168, 'playground', false, 'Kids will love our fun and safe playground'),
 (314, 238, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (315, 212, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (316, 73, 'playground', false, 'Kids will love our fun and safe playground'),
 (317, 9, 'playground', false, 'Kids will love our fun and safe playground'),
 (318, 41, 'parking', false, 'Convenient & secure parking available'),
 (319, 41, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (320, 58, 'parking', true, 'Convenient & secure parking available'),
 (321, 216, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (322, 256, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (323, 191, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (324, 67, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (325, 31, 'parking', true, 'Convenient & secure parking available'),
 (326, 201, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (327, 143, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (328, 216, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (329, 192, 'playground', false, 'Kids will love our fun and safe playground'),
 (330, 118, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (331, 267, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (332, 78, 'playground', false, 'Kids will love our fun and safe playground'),
 (333, 241, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (334, 160, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (335, 51, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (336, 56, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (337, 270, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (338, 100, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (339, 21, 'playground', true, 'Kids will love our fun and safe playground'),
 (340, 60, 'playground', false, 'Kids will love our fun and safe playground'),
 (341, 207, 'parking', false, 'Convenient & secure parking available'),
 (342, 233, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (343, 223, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (344, 94, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (345, 271, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (346, 90, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (347, 35, 'playground', false, 'Kids will love our fun and safe playground'),
 (348, 106, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (349, 206, 'playground', true, 'Kids will love our fun and safe playground'),
 (350, 33, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (351, 61, 'parking', true, 'Convenient & secure parking available'),
 (352, 192, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (353, 234, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (354, 63, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (355, 39, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (356, 17, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (357, 184, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (358, 82, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (359, 68, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (360, 77, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (361, 91, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (362, 260, 'parking', true, 'Convenient & secure parking available'),
 (363, 100, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (364, 9, 'parking', false, 'Convenient & secure parking available'),
 (365, 145, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (366, 217, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (367, 222, 'parking', true, 'Convenient & secure parking available'),
 (368, 202, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (369, 15, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (370, 119, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (371, 58, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (372, 183, 'parking', true, 'Convenient & secure parking available'),
 (373, 26, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (374, 246, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (375, 79, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (376, 243, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (377, 100, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (378, 152, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (379, 216, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (380, 90, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (381, 41, 'parking', true, 'Convenient & secure parking available'),
 (382, 111, 'parking', true, 'Convenient & secure parking available'),
 (383, 34, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (384, 203, 'playground', true, 'Kids will love our fun and safe playground'),
 (385, 125, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (386, 124, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (387, 99, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (388, 162, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (389, 98, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (390, 203, 'parking', false, 'Convenient & secure parking available'),
 (391, 227, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (392, 117, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (393, 52, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (394, 168, 'parking', false, 'Convenient & secure parking available'),
 (395, 120, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (396, 188, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (397, 181, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (398, 9, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (399, 181, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (400, 50, 'playground', false, 'Kids will love our fun and safe playground'),
 (401, 166, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (402, 7, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (403, 243, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (404, 158, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (405, 212, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (406, 260, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (407, 151, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (408, 60, 'playground', false, 'Kids will love our fun and safe playground'),
 (409, 174, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (410, 215, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (411, 186, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (412, 87, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (413, 6, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (414, 263, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (415, 267, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (416, 94, 'Wi-fi', true, 'Free high-speed Wi-Fi throughout the property'),
 (417, 148, 'playground', false, 'Kids will love our fun and safe playground'),
 (418, 220, 'playground', false, 'Kids will love our fun and safe playground'),
 (419, 162, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (420, 132, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (421, 226, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (422, 107, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (423, 9, 'Hot Tub', true, 'Unwind in our soothing hot tub'),
 (424, 272, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (425, 211, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (426, 232, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (427, 219, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (428, 81, 'parking', false, 'Convenient & secure parking available'),
 (429, 214, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (430, 72, 'playground', false, 'Kids will love our fun and safe playground'),
 (431, 69, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (432, 170, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (433, 79, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (434, 38, 'sauna', true, 'Relax and detox in our comfortable sauna'),
 (435, 210, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (436, 207, 'parking', true, 'Convenient & secure parking available'),
 (437, 64, 'playground', false, 'Kids will love our fun and safe playground'),
 (438, 216, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (439, 155, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (440, 204, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (441, 5, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (442, 252, 'parking', true, 'Convenient & secure parking available'),
 (443, 79, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (444, 253, 'playground', false, 'Kids will love our fun and safe playground'),
 (445, 242, 'playground', false, 'Kids will love our fun and safe playground'),
 (446, 136, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (447, 141, 'parking', true, 'Convenient & secure parking available'),
 (448, 18, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (449, 72, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (450, 137, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (451, 131, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (452, 94, 'playground', true, 'Kids will love our fun and safe playground'),
 (453, 199, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (454, 256, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (455, 145, 'playground', true, 'Kids will love our fun and safe playground'),
 (456, 206, 'playground', false, 'Kids will love our fun and safe playground'),
 (457, 101, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (458, 230, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (459, 157, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (460, 44, 'pool', true, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (461, 16, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (462, 131, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (463, 175, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (464, 77, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (465, 257, 'Wi-fi', false, 'Free high-speed Wi-Fi throughout the property'),
 (466, 204, 'gym', false, 'Access our fully-equipped gym to keep fit during your stay'),
 (467, 1, 'parking', true, 'Convenient & secure parking available'),
 (468, 108, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (469, 187, 'Fireplace', true, 'Enjoy the cozy warmth of our inviting fireplace'),
 (470, 163, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (471, 92, 'parking', true, 'Convenient & secure parking available'),
 (472, 227, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (473, 252, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (474, 257, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (475, 59, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (476, 268, 'sauna', false, 'Relax and detox in our comfortable sauna'),
 (477, 51, 'parking', false, 'Convenient & secure parking available'),
 (478, 54, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (479, 260, 'gym', true, 'Access our fully-equipped gym to keep fit during your stay'),
 (480, 183, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (481, 23, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (482, 96, 'Hot Tub', false, 'Unwind in our soothing hot tub'),
 (483, 169, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (484, 195, 'tennis court', false, 'Play tennis on our professional-grade court'),
 (485, 125, 'playground', false, 'Kids will love our fun and safe playground'),
 (486, 125, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (487, 68, 'parking', false, 'Convenient & secure parking available'),
 (488, 241, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (489, 269, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (490, 52, 'pool', false, 'Enjoy our refreshing swimming pool perfect for sunny days.'),
 (491, 44, 'Fireplace', false, 'Enjoy the cozy warmth of our inviting fireplace'),
 (492, 118, 'parking', true, 'Convenient & secure parking available'),
 (493, 80, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (494, 64, 'Pet Friendly', true, 'Pets are welcome to join the fun'),
 (495, 200, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (496, 93, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (497, 59, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (498, 12, 'tennis court', true, 'Play tennis on our professional-grade court'),
 (499, 259, 'Pet Friendly', false, 'Pets are welcome to join the fun'),
 (500, 7, 'Pet Friendly', true, 'Pets are welcome to join the fun');
 